demo pipeline with carbonara:
    folder: demo_pipeline_pesto
    antigen: demo.pdb
    epitope: A27-35
    steps:
    -   iteration 1:
            steps:
            -   generation:
                    steps:
                    -   rfdiffusion:
                            num_designs: 1
                            partial_T: 23
                            contacts_threshold: 5
                            rog_potential: 12
                    -   backbone_filtering:
                            ss_threshold: 4
                            rog_cutoff: 10
                    -   proteinmpnn:
                            seqs_per_target: 10
                            sampling_temp: .5
                            backbone_noise: .20
                            batch_size: 10
            -   validation:
                    steps:
                    -   omegafold:
                            num_recycles: 5
                            model_weights: 2
                    -   sequence_filtering:
                            name: 'omegafold_filtering'
                            model: 'omegafold'
                            plddt_threshold: 40
                            average_cutoff: 20
                            rog_cutoff: 10
                            max_samples: 200
                            max_folds_per_sample: 50
                    -   colabfold:
                            num_recycles: 3
                            model_name: 'alphafold2'
                            num_models: 5
                    -   sequence_filtering:
                            name: 'colabfold_filtering'
                            model: 'alphafold2'
                            plddt_threshold: 40
                            average_cutoff: 10
                            max_samples: 80
                    -   fold_collection:
                            model: 'alphafold2'
    -   iteration 2:
            steps:
            -   generation:
                    steps:
                    -   proteinmpnn:
                            seqs_per_target: 10
                            sampling_temp: .2
                            backbone_noise: .0
                            batch_size: 10
            -   validation:
                    steps:
                    -   omegafold:
                            num_recycles: 5
                            model_weights: 2
                    -   sequence_filtering:
                            name: 'omegafold_filtering'
                            model: 'omegafold'
                            plddt_threshold: 50
                            average_cutoff: 10
                            rog_cutoff: 10
                            max_samples: 100
                            max_folds_per_sample: 30
                    -   colabfold:
                            num_recycles: 3
                            model_name: 'alphafold2'
                            num_models: 5
                    -   sequence_filtering:
                            name: 'colabfold_filtering'
                            model: 'alphafold2'
                            plddt_threshold: 50
                            average_cutoff: 10
                            max_samples: 80
                            max_folds_per_sample: 50
                    -   fold_collection:
                            model: 'alphafold2'
    -   interactions:
            steps:
            -   pesto:
                    name: 'interactive_sites'
            -   interaction_window:
                    name: 'pesto_interaction_window'
                    offset: 4
                    interaction_key: 'pesto.interaction_prob'
